###############################################################################
## dev

server:
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  profiles:
    include:
      - console-logging
      - file-logging
    active: local
  #  task:
#    execution:
#      pool:
#        core-size: 50
#        max-size: 200
#        queue-capacity: 1000
#      thread-name-prefix: task-
#
#    scheduling:
#      pool:
#        size: 5
#      thread-name-prefix: scheduling-

  jpa:
    database: mysql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: on

# actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  info:
#    git:
#      mode: full

###############################################################################
## openAPI 3.0 - swagger
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

###############################################################################

api:
  base:
    domain: http://localhost:8081
